version: '2'

services:
  ci:
    build: .
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'


  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'apache_data:/bitnami/apache'
      - 'testlink_data:/bitnami/testlink'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  apache_data:
    driver: local
  testlink_data:
    driver: local
  jenkins_data:
    driver: local
